brenicillin/little-esty-shop

app/models/invoice.rb, app/models/invoice_item.rb, app/models/transaction.rb, db/migrate/20230410213403_create_invoices.rb, db/migrate/20230410213656_create_transactions.rb, db/migrate/20230410213740_create_invoice_items.rb, db/schema.rb
=> update migrations and implement enums

app/controllers/merchant/items_controller.rb, app/views/merchant/items/index.html.erb, app/views/merchant/items/show.html.erb, spec/factories/items.rb, spec/features/merchants/dashboard/show_spec.rb, spec/features/merchants/index_spec.rb
Howdy y'all. User story 7 complete, Merchant items show page has links to items' show pages
=> Merchant Items are links to item show page

app/controllers/merchant/invoice_controller.rb, app/views/merchant/dashboard/show.html.erb, config/routes.rb, spec/features/merchants/dashboard/show_spec.rb
US2 complete, links added to merchant dashboard show page
=> 2 user story 2 merchant dashboard links

app/controllers/merchant/items_controller.rb, app/models/item.rb, app/views/merchant/items/index.html.erb, spec/features/merchants/items/index_spec.rb, spec/models/item_spec.rb
Created a class method for items to group them in to either enabled or disabled items.
Adjust controller index to call on either enabled or disabled items. 
Rework the view page to group items by enabled or disabled. 
Write tests for model and features. 
Yay team!
=> 10 user story 10 merchant items grouped by status

app/controllers/merchant/dashboard_controller.rb, app/controllers/merchant/invoices_controller.rb, app/models/invoice_item.rb, app/views/merchant/dashboard/show.html.erb, spec/features/merchants/dashboard/show_spec.rb, spec/models/invoice_item_spec.rb
=> 4 user story 4 merchant dashboard items ready to ship

app/controllers/merchant/invoices_controller.rb, app/models/merchant.rb, app/views/merchant/invoices/show.html.erb, spec/features/merchants/dashboard/show_spec.rb, spec/features/merchants/invoices/show_spec.rb, spec/models/invoice_item_spec.rb, spec/models/merchant_spec.rb
fix tests and complete user story 15
=> 15 user story 15 merchant invoice show page

app/controllers/merchant/items_controller.rb, app/views/merchant/items/_form.html.erb, app/views/merchant/items/edit.html.erb, app/views/merchant/items/index.html.erb, app/views/merchant/items/new.html.erb, spec/features/merchants/items/index_spec.rb
Add a link to the merchant items index page to create a new item
Create a new items page
Create a partial form
Change edit to include partial
Write tests for new item creation
=> 11 user story 11 merchant item create

spec/features/merchants/invoices/index_spec.rb
change the test to get rid of annoying capybara errors
=> fix tests to avoid capybara notices in terminal

app/controllers/admin/dashboard_controller.rb, app/controllers/admin/invoices_controller.rb, app/controllers/admin/merchants_controller.rb, app/views/admin/dashboard/index.html.erb, app/views/admin/invoices/index.html.erb, app/views/admin/merchants/index.html.erb, config/routes.rb, spec/features/admin/dashboard/index_spec.rb
Create links to merchants and invoices on the admin dashboard
Create controllers for both admin/merchants and admin/invoices
Created view page for both.
Write tests for both links
=> Add links to admin/merchants and admin/invoices

app/controllers/merchant/items_controller.rb, app/models/invoice.rb, app/models/invoice_item.rb, app/models/item.rb, app/models/transaction.rb, app/views/merchant/items/index.html.erb, spec/features/merchants/items/index_spec.rb, spec/models/item_spec.rb
Merchant items index page includes div with information about top 5 revenue-creating items
=> 12 user story 12 merchant items index 5 most popular items

app/controllers/admin/dashboard_controller.rb, app/models/customer.rb, app/models/item.rb, app/models/transaction.rb, app/views/admin/dashboard/index.html.erb, spec/features/admin/dashboard/index_spec.rb, spec/models/customer_spec.rb, spec/models/item_spec.rb
Created a statistics section in the admin/merchants dashboard which shows top_five customers
=> 21 user story 21 admin dashboard statistics top customers 1

app/models/invoice.rb, app/views/admin/dashboard/index.html.erb, spec/features/admin/dashboard/index_spec.rb, spec/models/invoice_spec.rb
Just a quick edit to incomplete invoices to order them by date created at with tests
=> 23 user story 23 admin dashboard invoices sorted by least recent

app/controllers/invoice_items_controller.rb, app/controllers/merchant/invoices_controller.rb, app/models/invoice_item.rb, app/models/item.rb, app/views/merchant/invoices/show.html.erb, config/routes.rb, spec/features/merchants/invoices/show_spec.rb, spec/models/invoice_item_spec.rb, spec/models/item_spec.rb
finally got that darn update button to work
=> 18 user story 18 merchant invoice show page update item status

app/controllers/admin/dashboard_controller.rb, app/controllers/admin/merchants_controller.rb, app/views/admin/merchants/index.html.erb, app/views/admin/merchants/show.html.erb, spec/features/admin/merchants/index_spec.rb, spec/features/admin/merchants/show_spec.rb
=> 25 user story 25 admin merchant show

app/views/admin/invoices/index.html.erb, spec/features/admin/invoices/index_spec.rb
=> 32 user story 32 admin invoices index page

app/views/admin/invoices/show.html.erb, spec/features/admin/invoices/show_spec.rb
Quick edits to the admin invoice show page with some tests
=> 33 user story 33 admin invoice show page

app/controllers/admin/invoices_controller.rb, app/views/admin/invoices/show.html.erb, spec/features/admin/invoices/show_spec.rb
essentially 18 all over again, without the hard button part
=> 34 user story 34 admin invoice show page invoice item information

app/controllers/admin/merchants_controller.rb, app/views/admin/merchants/edit.html.erb, app/views/admin/merchants/show.html.erb, spec/features/admin/invoices/index_spec.rb, spec/features/admin/merchants/edit_spec.rb, spec/features/admin/merchants/show_spec.rb
edit and update for admin merchants
=> 26 user story 26 admin merchant update

app/controllers/admin/invoices_controller.rb, app/views/admin/invoices/show.html.erb, spec/features/admin/invoices/show_spec.rb
trucking through this stuff good work everyone
=> 36 user story 36 admin invoice show page update invoice status

app/controllers/admin/merchants_controller.rb, app/models/merchant.rb, app/views/admin/invoices/show.html.erb, app/views/admin/merchants/index.html.erb, app/views/merchant/items/index.html.erb, spec/features/admin/merchants/index_spec.rb
mostly just splitting dyson's last work into enabled and disabled and formatting
=> 28 user story 28 admin merchants grouped by status

app/controllers/admin/merchants_controller.rb, app/views/admin/merchants/index.html.erb, app/views/admin/merchants/new.html.erb, app/views/admin/merchants/show.html.erb, app/views/layouts/application.html.erb, spec/features/admin/merchants/edit_spec.rb, spec/features/admin/merchants/index_spec.rb, spec/features/admin/merchants/new_spec.rb, spec/models/merchant_spec.rb
Add "Add New Merchant" link to Admin merchants index page with corresponding view and tests, also added a flash message that I forgot to put in for user story 26
=> 29 user story 29 admin merchant create

app/controllers/merchant/items_controller.rb, app/models/item.rb, app/views/merchant/items/index.html.erb, spec/features/merchants/items/index_spec.rb, spec/models/item_spec.rb
Create a method for top day for the items index page to be shown below each of the top 5 items. 
Write model tests
Write features tests
=> 13 user story 13 merchant items index top items best day

app/controllers/admin/merchants_controller.rb, app/controllers/merchant/items_controller.rb, app/models/item.rb, app/models/merchant.rb, app/models/transaction.rb, app/views/admin/dashboard/index.html.erb, app/views/admin/merchants/index.html.erb, spec/features/admin/dashboard/index_spec.rb, spec/features/admin/merchants/index_spec.rb, spec/features/merchants/items/index_spec.rb, spec/models/item_spec.rb, spec/models/merchant_spec.rb
write top day for merchants, fix top day for items, write tests for models and features, move stuff from dashboard to merchant index. 
GO TEAM!!
=> 31 user story 31 admin merchants top merchants best day

app/assets/stylesheets/application.css, app/views/layouts/application.html.erb, app/views/merchant/items/_header.html.erb, app/views/merchant/items/index.html.erb
CSS and HTML formatting for Merchant Items index page. 
Stylin'
=> style merchant/items page

app/assets/stylesheets/application.css, app/controllers/admin/dashboard_controller.rb, app/controllers/admin/invoices_controller.rb, app/controllers/application_controller.rb, app/controllers/merchant/dashboard_controller.rb, app/controllers/merchant/invoices_controller.rb, app/controllers/merchant/items_controller.rb, app/services/photo_builder.rb, app/services/photo_service.rb, app/views/layouts/application.html.erb, app/views/merchant/items/_header.html.erb
=> app logo and made size perfect

app/views/admin/invoices/_header.html.erb, app/views/admin/invoices/index.html.erb
=> admin invoice index styled

app/assets/stylesheets/application.css, app/poros/photo.rb, app/views/merchant/invoices/_header.html.erb, app/views/merchant/invoices/index.html.erb, app/views/merchant/items/index.html.erb
add styling to merchant invoices, create a partial for the header
=> 93 fe formatting merchant invoices index

app/models/invoice.rb, app/models/invoice_item.rb, app/views/admin/invoices/_header.html.erb, app/views/admin/invoices/index.html.erb, app/views/admin/invoices/show.html.erb, spec/models/invoice_item_spec.rb, spec/models/invoice_spec.rb
=> add conversion for unit prices and style admin invoice show page

app/models/merchant.rb, app/views/admin/merchants/_header.html.erb, app/views/admin/merchants/index.html.erb, spec/models/merchant_spec.rb
=> format admin merchant index and format currency for that view

app/views/admin/merchants/_header.html.erb, app/views/admin/merchants/show.html.erb, spec/features/admin/invoices/index_spec.rb, spec/features/admin/invoices/show_spec.rb
=> update tests and style merchant show page, rate limit exceeded :(

app/controllers/welcome_controller.rb
=> add app_logo to welcome controller

spec/features/merchants/items/index_spec.rb
put tests back in for a new item creation
=> put tests for creating new item back in to test suite
